package org.paddy.stockmarket;

import java.awt.event.KeyEvent;
import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.util.HashSet;
import java.util.Iterator;
import java.util.List;
import javax.swing.JOptionPane;
import org.paddy.stockmarket.util.json.Query;
import org.paddy.stockmarket.util.json.Quote;
import org.paddy.stockmarket.util.json.Results;

/**
 *
 * @author paddy
 */
public class StockManagerDialog extends javax.swing.JDialog 
{
    public static final long serialVersionUID = 12345667890L;
    HashSet<String> stocksymbols;
    /**
     * Creates new form StockManagerDialog
     */
    public StockManagerDialog(java.awt.Frame parent, boolean modal)
    {
        super(parent, "Manage stocks", modal);
        initComponents();
    }
    /**
     * 
     * @param stocksymbols HashSet<String>
     */
    protected void setSymbols(HashSet<String> stocksymbols)
    {
        this.stocksymbols = stocksymbols;
    }
    /**
     * 
     */
    private void searchStock()
    {
        String searchString = addStockSearchTextField.getText();
        if(searchString.equals("Enter a yahoo stock symbol") || searchString.equals(""))
        {
            addStockSearchButton.setToolTipText("You should enter a yahoo stock symbol first");
        }
        else
        {
            boolean yahooFinanceQuotesBlocked = false;
            Query query = null;
            addStockSearchButton.setToolTipText("Last search was: " + searchString);
            try
            {
                String YQLqueryString, GETparam, request;
                YQLqueryString = URLEncoder.encode("select * " +
                                                        "from yahoo.finance.quotes " +
                                                        "where symbol = \"" + 
                                                        searchString +
                                                        "\" | sort(field=\"Name\", descending=\"false\")", "UTF-8");
                GETparam = YQLquery.GETparam + URLEncoder.encode("http://datatables.org/alltables.env", "UTF-8");
                request = YQLquery.requestURI + YQLqueryString + GETparam;
                query = YQLquery.yqlQueryResult(request);
            }
            catch(UnsupportedEncodingException uee)
            {
                    System.err.println(uee);
            }
            Results results = query.getResults();
            if(results == null)
            {
                yahooFinanceQuotesBlocked = true;
                String diagnostics = YQLquery.getDiagnostics(query);
                JOptionPane.showMessageDialog(this,
                    diagnostics,
                    "YAHOO Errog",
                    JOptionPane.ERROR_MESSAGE);
            }
            else
            {
                String symbol, name, bidRealtime, lastTradePriceOnly, bidString;
                Quote quote = results.getQuote();
                symbol = quote.getSymbol();
                name = quote.getName();
                bidRealtime = quote.getBidRealtime();
                lastTradePriceOnly = quote.getLastTradePriceOnly();
                bidString = quote.getBid();
                float bid;
                bid = (float) 0;
                if(bidRealtime != null)
                {
                    try
                    {
                        bid = Float.parseFloat(bidRealtime);
                    }
                    catch(NumberFormatException nfe)
                    {
                        System.err.println(nfe);
                    }
                }
                else if(lastTradePriceOnly != null)
                {
                    try
                    {
                        bid = Float.parseFloat(lastTradePriceOnly);
                    }
                    catch(NumberFormatException nfe)
                    {
                        System.err.println(nfe);
                    }
                }
                else if(bidString != null)
                {
                    try
                    {
                        bid = Float.parseFloat(bidString);
                    }
                    catch(NumberFormatException nfe)
                    {
                        System.err.println(nfe);
                    }
                }
                else
                {
                        System.out.println("BidRealtime is null for: " + name + " " + lastTradePriceOnly);
                }
                System.out.println(name + " " + symbol + " " + bid);
            }  
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        stockManagerTabbedPane = new javax.swing.JTabbedPane();
        currentStocksScrollPane = new javax.swing.JScrollPane();
        currentStocksPanel = new javax.swing.JPanel();
        addStockPanel = new javax.swing.JPanel();
        addStockSearchLabel = new javax.swing.JLabel();
        addStockSearchTextField = new javax.swing.JTextField();
        addStockSearchButton = new javax.swing.JButton();

        stockManagerTabbedPane.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                stockManagerTabbedPaneStateChanged(evt);
            }
        });

        currentStocksPanel.setPreferredSize(new java.awt.Dimension(600, 300));
        currentStocksPanel.setRequestFocusEnabled(false);

        javax.swing.GroupLayout currentStocksPanelLayout = new javax.swing.GroupLayout(currentStocksPanel);
        currentStocksPanel.setLayout(currentStocksPanelLayout);
        currentStocksPanelLayout.setHorizontalGroup(
            currentStocksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        currentStocksPanelLayout.setVerticalGroup(
            currentStocksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        currentStocksScrollPane.setViewportView(currentStocksPanel);

        stockManagerTabbedPane.addTab("Current stocks", currentStocksScrollPane);

        addStockPanel.setForeground(new java.awt.Color(255, 255, 255));
        addStockPanel.setName("addStockPanel"); // NOI18N

        addStockSearchLabel.setText("Stock Symbol:");
        addStockSearchLabel.setPreferredSize(new java.awt.Dimension(100, 15));

        addStockSearchTextField.setText("Enter a yahoo stock symbol");
        addStockSearchTextField.setToolTipText("Enter a yahoo stock symbol");
        addStockSearchTextField.setPreferredSize(new java.awt.Dimension(500, 25));
        addStockSearchTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                textFieldMouseEntered(evt);
            }
        });
        addStockSearchTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStockSearchTextFieldActionPerformed(evt);
            }
        });
        addStockSearchTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textFieldKeyPressed(evt);
            }
        });

        addStockSearchButton.setText("Lookup");
        addStockSearchButton.setMargin(new java.awt.Insets(2, 2, 2, 2));
        addStockSearchButton.setPreferredSize(new java.awt.Dimension(75, 25));
        addStockSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addStockPanelLayout = new javax.swing.GroupLayout(addStockPanel);
        addStockPanel.setLayout(addStockPanelLayout);
        addStockPanelLayout.setHorizontalGroup(
            addStockPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addStockPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addStockSearchLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addStockSearchTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(addStockSearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        addStockPanelLayout.setVerticalGroup(
            addStockPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addStockPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addStockPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addStockSearchLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addStockSearchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addStockSearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        stockManagerTabbedPane.addTab("Add stock", addStockPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(stockManagerTabbedPane)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(stockManagerTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addStockSearchTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStockSearchTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addStockSearchTextFieldActionPerformed

    private void textFieldMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textFieldMouseEntered
        if(addStockSearchTextField.getText().equals("Enter a yahoo stock symbol"))
        {
            addStockSearchTextField.setText(null);
        }
    }//GEN-LAST:event_textFieldMouseEntered

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        if(evt.getActionCommand().equals("Lookup"))
        {
            searchStock();
        }
    }//GEN-LAST:event_searchButtonActionPerformed

    private void stockManagerTabbedPaneStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_stockManagerTabbedPaneStateChanged
        int index = stockManagerTabbedPane.getSelectedIndex();
        if(index == 1)
        {
            this.getRootPane().setDefaultButton(addStockSearchButton);
            addStockSearchButton.requestFocus();
        }
    }//GEN-LAST:event_stockManagerTabbedPaneStateChanged

    private void textFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFieldKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            searchStock();
        }    
    }//GEN-LAST:event_textFieldKeyPressed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addStockPanel;
    private javax.swing.JButton addStockSearchButton;
    private javax.swing.JLabel addStockSearchLabel;
    private javax.swing.JTextField addStockSearchTextField;
    private javax.swing.JPanel currentStocksPanel;
    private javax.swing.JScrollPane currentStocksScrollPane;
    private javax.swing.JTabbedPane stockManagerTabbedPane;
    // End of variables declaration//GEN-END:variables
}