package org.paddy.stockmarket;

import java.util.HashSet;

/**
 *
 * @author paddy
 */
public class StockManagerDialog extends javax.swing.JDialog {
    public static final long serialVersionUID = 12345667890L;
    HashSet<String> stocksymbols;
    /**
     * Creates new form StockManagerDialog
     */
    public StockManagerDialog(java.awt.Frame parent, boolean modal) {
        super(parent, "Manage stocks", modal);
        initComponents();
    }
    /**
     * 
     * @param stocksymbols HashSet<String>
     */
    protected void setSymbols(HashSet<String> stocksymbols)
    {
        this.stocksymbols = stocksymbols;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}