package org.paddy.stockmarket;

import java.util.HashSet;

/**
 *
 * @author paddy
 */
public class stockManagerDialog extends javax.swing.JDialog 
{
    public static final long serialVersionUID = 12345667890L;
    HashSet<String> stocksymbols;
    /**
     * Creates new form stockManagerDialog
     */
    public stockManagerDialog(java.awt.Frame parent, boolean modal)
    {
        super(parent, "Manage stocks", modal);
        initComponents();
    }
    /**
     * 
     * @param stocksymbols HashSet<String>
     */
    protected void setSymbols(HashSet<String> stocksymbols)
    {
        this.stocksymbols = stocksymbols;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        stockManagerTabbedPane = new javax.swing.JTabbedPane();
        currenTStocksScrollPane = new javax.swing.JScrollPane();
        currentStocksPanel = new javax.swing.JPanel();
        addStockPanel = new javax.swing.JPanel();
        addStockSearchLabel = new javax.swing.JLabel();
        addStockSearchTextField = new javax.swing.JTextField();
        addStockSearchButton = new javax.swing.JButton();

        currentStocksPanel.setPreferredSize(new java.awt.Dimension(600, 300));
        currentStocksPanel.setRequestFocusEnabled(false);

        javax.swing.GroupLayout currentStocksPanelLayout = new javax.swing.GroupLayout(currentStocksPanel);
        currentStocksPanel.setLayout(currentStocksPanelLayout);
        currentStocksPanelLayout.setHorizontalGroup(
            currentStocksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        currentStocksPanelLayout.setVerticalGroup(
            currentStocksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        currenTStocksScrollPane.setViewportView(currentStocksPanel);

        stockManagerTabbedPane.addTab("Current stocks", currenTStocksScrollPane);

        addStockPanel.setForeground(new java.awt.Color(255, 255, 255));

        addStockSearchLabel.setText("Search for stocks:");
        addStockSearchLabel.setPreferredSize(new java.awt.Dimension(100, 15));

        addStockSearchTextField.setText("Enter a search string");
        addStockSearchTextField.setToolTipText("Enter a search string");
        addStockSearchTextField.setPreferredSize(new java.awt.Dimension(500, 25));
        addStockSearchTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                clearTextField(evt);
            }
        });
        addStockSearchTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStockSearchTextFieldActionPerformed(evt);
            }
        });

        addStockSearchButton.setText("Search");
        addStockSearchButton.setMargin(new java.awt.Insets(2, 2, 2, 2));
        addStockSearchButton.setPreferredSize(new java.awt.Dimension(75, 25));

        javax.swing.GroupLayout addStockPanelLayout = new javax.swing.GroupLayout(addStockPanel);
        addStockPanel.setLayout(addStockPanelLayout);
        addStockPanelLayout.setHorizontalGroup(
            addStockPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addStockPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addStockSearchLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addStockSearchTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(addStockSearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        addStockPanelLayout.setVerticalGroup(
            addStockPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addStockPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addStockPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addStockSearchLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addStockSearchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addStockSearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        stockManagerTabbedPane.addTab("Add stock", addStockPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(stockManagerTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 618, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(stockManagerTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addStockSearchTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStockSearchTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addStockSearchTextFieldActionPerformed

    private void clearTextField(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearTextField
        if(addStockSearchTextField.getText().equals("Enter a search string"))
        {
            addStockSearchTextField.setText(null);
        }
    }//GEN-LAST:event_clearTextField

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addStockPanel;
    private javax.swing.JButton addStockSearchButton;
    private javax.swing.JLabel addStockSearchLabel;
    private javax.swing.JTextField addStockSearchTextField;
    private javax.swing.JScrollPane currenTStocksScrollPane;
    private javax.swing.JPanel currentStocksPanel;
    private javax.swing.JTabbedPane stockManagerTabbedPane;
    // End of variables declaration//GEN-END:variables
}
