/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.paddy.stockmarket.util.json;
/**
 * Autogenerated code in Quote.java with php script:
 * <pre>
 * <?php
 * $availableFields= array('Ask','AverageDailyVolume','Bid','AskRealtime','BidRealtime','BookValue','Change&PercentChange','Change','Commission','ChangeRealtime','AfterHoursChangeRealtime','DividendShare','LastTradeDate','TradeDate','E~
 * foreach($availableFields as $value)
 * {
 *         echo '    /**
 *      *
 *      &lowast;/
 *     protected String ' . $value . ';' . PHP_EOL;
 * }
 * foreach($availableFields as $value)
 * {
 *         echo '    /**
 *      *
 *      * @return String ' . $value  . '
 *      &lowast;/
 *     public String get' . $value . '()
 *     {
 *             return ' . $value . ';
 *     }' . PHP_EOL;
 * }
 * foreach($availableFields as $value)
 * {
 *         echo '    /**
 *      *
 *      * @param ' . $value . ' String
 *      &lowast;/
 *     public void set' . $value . '(String ' . $value . ')
 *     {
 *         this.' . $value . ' = ' . $value . ';
 *     }' . PHP_EOL;
 * }
 * ?>
 * </pre>
 * @author paddy (Patrick-Emil Zörner)
 */
public class Quote
{
    /**
     *
     */
    protected String Ask;
    /**
     *
     */
    protected String AverageDailyVolume;
    /**
     *
     */
    protected String Bid;
    /**
     *
     */
    protected String AskRealtime;
    /**
     *
     */
    protected String BidRealtime;
    /**
     *
     */
    protected String BookValue;
    /**
     * NB: this is actually called Change&PercentChange might not work like this
     */
    protected String ChangePercentChange;
    /**
     *
     */
    protected String Change;
    /**
     *
     */
    protected String Commission;
    /**
     *
     */
    protected String ChangeRealtime;
    /**
     *
     */
    protected String AfterHoursChangeRealtime;
    /**
     *
     */
    protected String DividendShare;
    /**
     *
     */
    protected String LastTradeDate;
    /**
     *
     */
    protected String TradeDate;
    /**
     *
     */
    protected String EarningsShare;
    /**
     *
     */
    protected String ErrorIndicationreturnedforsymbolchangedinvalid;
    /**
     *
     */
    protected String EPSEstimateCurrentYear;
    /**
     *
     */
    protected String EPSEstimateNextYear;
    /**
     *
     */
    protected String EPSEstimateNextQuarter;
    /**
     *
     */
    protected String DaysLow;
    /**
     *
     */
    protected String DaysHigh;
    /**
     *
     */
    protected String YearLow;
    /**
     *
     */
    protected String YearHigh;
    /**
     *
     */
    protected String HoldingsGainPercent;
    /**
     *
     */
    protected String AnnualizedGain;
    /**
     *
     */
    protected String HoldingsGain;
    /**
     *
     */
    protected String HoldingsGainPercentRealtime;
    /**
     *
     */
    protected String HoldingsGainRealtime;
    /**
     *
     */
    protected String MoreInfo;
    /**
     *
     */
    protected String OrderBookRealtime;
    /**
     *
     */
    protected String MarketCapitalization;
    /**
     *
     */
    protected String MarketCapRealtime;
    /**
     *
     */
    protected String EBITDA;
    /**
     *
     */
    protected String ChangeFromYearLow;
    /**
     *
     */
    protected String PercentChangeFromYearLow;
    /**
     *
     */
    protected String LastTradeRealtimeWithTime;
    /**
     *
     */
    protected String ChangePercentRealtime;
    /**
     *
     */
    protected String ChangeFromYearHigh;
    /**
     *
     */
    protected String PercebtChangeFromYearHigh;
    /**
     *
     */
    protected String LastTradeWithTime;
    /**
     *
     */
    protected String LastTradePriceOnly;
    /**
     *
     */
    protected String HighLimit;
    /**
     *
     */
    protected String LowLimit;
    /**
     *
     */
    protected String DaysRange;
    /**
     *
     */
    protected String DaysRangeRealtime;
    /**
     *
     */
    protected String FiftydayMovingAverage;
    /**
     *
     */
    protected String TwoHundreddayMovingAverage;
    /**
     *
     */
    protected String ChangeFromTwoHundreddayMovingAverage;
    /**
     *
     */
    protected String PercentChangeFromTwoHundreddayMovingAverage;
    /**
     *
     */
    protected String ChangeFromFiftydayMovingAverage;
    /**
     *
     */
    protected String PercentChangeFromFiftydayMovingAverage;
    /**
     *
     */
    protected String Name;
    /**
     *
     */
    protected String Notes;
    /**
     *
     */
    protected String Open;
    /**
     *
     */
    protected String PreviousClose;
    /**
     *
     */
    protected String PricePaid;
    /**
     *
     */
    protected String ChangeinPercent;
    /**
     *
     */
    protected String PriceSales;
    /**
     *
     */
    protected String PriceBook;
    /**
     *
     */
    protected String ExDividendDate;
    /**
     *
     */
    protected String PERatio;
    /**
     *
     */
    protected String DividendPayDate;
    /**
     *
     */
    protected String PERatioRealtime;
    /**
     *
     */
    protected String PEGRatio;
    /**
     *
     */
    protected String PriceEPSEstimateCurrentYear;
    /**
     *
     */
    protected String PriceEPSEstimateNextYear;
    /**
     *
     */
    protected String Symbol;
    /**
     *
     */
    protected String SharesOwned;
    /**
     *
     */
    protected String ShortRatio;
    /**
     *
     */
    protected String LastTradeTime;
    /**
     *
     */
    protected String TickerTrend;
    /**
     *
     */
    protected String OneyrTargetPrice;
    /**
     *
     */
    protected String Volume;
    /**
     *
     */
    protected String HoldingsValue;
    /**
     *
     */
    protected String HoldingsValueRealtime;
    /**
     *
     */
    protected String YearRange;
    /**
     *
     */
    protected String DaysValueChange;
    /**
     *
     */
    protected String DaysValueChangeRealtime;
    /**
     *
     */
    protected String StockExchange;
    /**
     *
     */
    protected String DividendYield;
    /**
     *
     * @return String Ask
     */
    public String getAsk()
    {
            return Ask;
    }
    /**
     *
     * @return String AverageDailyVolume
     */
    public String getAverageDailyVolume()
    {
            return AverageDailyVolume;
    }
    /**
     *
     * @return String Bid
     */
    public String getBid()
    {
            return Bid;
    }
    /**
     *
     * @return String AskRealtime
     */
    public String getAskRealtime()
    {
            return AskRealtime;
    }
    /**
     *
     * @return String BidRealtime
     */
    public String getBidRealtime()
    {
            return BidRealtime;
    }
    /**
     *
     * @return String BookValue
     */
    public String getBookValue()
    {
            return BookValue;
    }
    /**
     * NB: this is actually called Change&PercentChange might not work like this
     * @return String ChangePercentChange
     */
    public String getChangePercentChange()
    {
            return ChangePercentChange;
    }
    /**
     *
     * @return String Change
     */
    public String getChange()
    {
            return Change;
    }
    /**
     *
     * @return String Commission
     */
    public String getCommission()
    {
            return Commission;
    }
    /**
     *
     * @return String ChangeRealtime
     */
    public String getChangeRealtime()
    {
            return ChangeRealtime;
    }
    /**
     *
     * @return String AfterHoursChangeRealtime
     */
    public String getAfterHoursChangeRealtime()
    {
            return AfterHoursChangeRealtime;
    }
    /**
     *
     * @return String DividendShare
     */
    public String getDividendShare()
    {
            return DividendShare;
    }
    /**
     *
     * @return String LastTradeDate
     */
    public String getLastTradeDate()
    {
            return LastTradeDate;
    }
    /**
     *
     * @return String TradeDate
     */
    public String getTradeDate()
    {
            return TradeDate;
    }
    /**
     *
     * @return String EarningsShare
     */
    public String getEarningsShare()
    {
            return EarningsShare;
    }
    /**
     *
     * @return String ErrorIndicationreturnedforsymbolchangedinvalid
     */
    public String getErrorIndicationreturnedforsymbolchangedinvalid()
    {
            return ErrorIndicationreturnedforsymbolchangedinvalid;
    }
    /**
     *
     * @return String EPSEstimateCurrentYear
     */
    public String getEPSEstimateCurrentYear()
    {
            return EPSEstimateCurrentYear;
    }
    /**
     *
     * @return String EPSEstimateNextYear
     */
    public String getEPSEstimateNextYear()
    {
            return EPSEstimateNextYear;
    }
    /**
     *
     * @return String EPSEstimateNextQuarter
     */
    public String getEPSEstimateNextQuarter()
    {
            return EPSEstimateNextQuarter;
    }
    /**
     *
     * @return String DaysLow
     */
    public String getDaysLow()
    {
            return DaysLow;
    }
    /**
     *
     * @return String DaysHigh
     */
    public String getDaysHigh()
    {
            return DaysHigh;
    }
    /**
     *
     * @return String YearLow
     */
    public String getYearLow()
    {
            return YearLow;
    }
    /**
     *
     * @return String YearHigh
     */
    public String getYearHigh()
    {
            return YearHigh;
    }
    /**
     *
     * @return String HoldingsGainPercent
     */
    public String getHoldingsGainPercent()
    {
            return HoldingsGainPercent;
    }
    /**
     *
     * @return String AnnualizedGain
     */
    public String getAnnualizedGain()
    {
            return AnnualizedGain;
    }
    /**
     *
     * @return String HoldingsGain
     */
    public String getHoldingsGain()
    {
            return HoldingsGain;
    }
    /**
     *
     * @return String HoldingsGainPercentRealtime
     */
    public String getHoldingsGainPercentRealtime()
    {
            return HoldingsGainPercentRealtime;
    }
    /**
     *
     * @return String HoldingsGainRealtime
     */
    public String getHoldingsGainRealtime()
    {
            return HoldingsGainRealtime;
    }
    /**
     *
     * @return String MoreInfo
     */
    public String getMoreInfo()
    {
            return MoreInfo;
    }
    /**
     *
     * @return String OrderBookRealtime
     */
    public String getOrderBookRealtime()
    {
            return OrderBookRealtime;
    }
    /**
     *
     * @return String MarketCapitalization
     */
    public String getMarketCapitalization()
    {
            return MarketCapitalization;
    }
    /**
     *
     * @return String MarketCapRealtime
     */
    public String getMarketCapRealtime()
    {
            return MarketCapRealtime;
    }
    /**
     *
     * @return String EBITDA
     */
    public String getEBITDA()
    {
            return EBITDA;
    }
    /**
     *
     * @return String ChangeFromYearLow
     */
    public String getChangeFromYearLow()
    {
            return ChangeFromYearLow;
    }
    /**
     *
     * @return String PercentChangeFromYearLow
     */
    public String getPercentChangeFromYearLow()
    {
            return PercentChangeFromYearLow;
    }
    /**
     *
     * @return String LastTradeRealtimeWithTime
     */
    public String getLastTradeRealtimeWithTime()
    {
            return LastTradeRealtimeWithTime;
    }
    /**
     *
     * @return String ChangePercentRealtime
     */
    public String getChangePercentRealtime()
    {
            return ChangePercentRealtime;
    }
    /**
     *
     * @return String ChangeFromYearHigh
     */
    public String getChangeFromYearHigh()
    {
            return ChangeFromYearHigh;
    }
    /**
     *
     * @return String PercebtChangeFromYearHigh
     */
    public String getPercebtChangeFromYearHigh()
    {
            return PercebtChangeFromYearHigh;
    }
    /**
     *
     * @return String LastTradeWithTime
     */
    public String getLastTradeWithTime()
    {
            return LastTradeWithTime;
    }
    /**
     *
     * @return String LastTradePriceOnly
     */
    public String getLastTradePriceOnly()
    {
            return LastTradePriceOnly;
    }
    /**
     *
     * @return String HighLimit
     */
    public String getHighLimit()
    {
            return HighLimit;
    }
    /**
     *
     * @return String LowLimit
     */
    public String getLowLimit()
    {
            return LowLimit;
    }
    /**
     *
     * @return String DaysRange
     */
    public String getDaysRange()
    {
            return DaysRange;
    }
    /**
     *
     * @return String DaysRangeRealtime
     */
    public String getDaysRangeRealtime()
    {
            return DaysRangeRealtime;
    }
    /**
     *
     * @return String FiftydayMovingAverage
     */
    public String getFiftydayMovingAverage()
    {
            return FiftydayMovingAverage;
    }
    /**
     *
     * @return String TwoHundreddayMovingAverage
     */
    public String getTwoHundreddayMovingAverage()
    {
            return TwoHundreddayMovingAverage;
    }
    /**
     *
     * @return String ChangeFromTwoHundreddayMovingAverage
     */
    public String getChangeFromTwoHundreddayMovingAverage()
    {
            return ChangeFromTwoHundreddayMovingAverage;
    }
    /**
     *
     * @return String PercentChangeFromTwoHundreddayMovingAverage
     */
    public String getPercentChangeFromTwoHundreddayMovingAverage()
    {
            return PercentChangeFromTwoHundreddayMovingAverage;
    }
    /**
     *
     * @return String ChangeFromFiftydayMovingAverage
     */
    public String getChangeFromFiftydayMovingAverage()
    {
            return ChangeFromFiftydayMovingAverage;
    }
    /**
     *
     * @return String PercentChangeFromFiftydayMovingAverage
     */
    public String getPercentChangeFromFiftydayMovingAverage()
    {
            return PercentChangeFromFiftydayMovingAverage;
    }
    /**
     *
     * @return String Name
     */
    public String getName()
    {
            return Name;
    }
    /**
     *
     * @return String Notes
     */
    public String getNotes()
    {
            return Notes;
    }
    /**
     *
     * @return String Open
     */
    public String getOpen()
    {
            return Open;
    }
    /**
     *
     * @return String PreviousClose
     */
    public String getPreviousClose()
    {
            return PreviousClose;
    }
    /**
     *
     * @return String PricePaid
     */
    public String getPricePaid()
    {
            return PricePaid;
    }
    /**
     *
     * @return String ChangeinPercent
     */
    public String getChangeinPercent()
    {
            return ChangeinPercent;
    }
    /**
     *
     * @return String PriceSales
     */
    public String getPriceSales()
    {
            return PriceSales;
    }
    /**
     *
     * @return String PriceBook
     */
    public String getPriceBook()
    {
            return PriceBook;
    }
    /**
     *
     * @return String ExDividendDate
     */
    public String getExDividendDate()
    {
            return ExDividendDate;
    }
    /**
     *
     * @return String PERatio
     */
    public String getPERatio()
    {
            return PERatio;
    }
    /**
     *
     * @return String DividendPayDate
     */
    public String getDividendPayDate()
    {
            return DividendPayDate;
    }
    /**
     *
     * @return String PERatioRealtime
     */
    public String getPERatioRealtime()
    {
            return PERatioRealtime;
    }
    /**
     *
     * @return String PEGRatio
     */
    public String getPEGRatio()
    {
            return PEGRatio;
    }
    /**
     *
     * @return String PriceEPSEstimateCurrentYear
     */
    public String getPriceEPSEstimateCurrentYear()
    {
            return PriceEPSEstimateCurrentYear;
    }
    /**
     *
     * @return String PriceEPSEstimateNextYear
     */
    public String getPriceEPSEstimateNextYear()
    {
            return PriceEPSEstimateNextYear;
    }
    /**
     *
     * @return String Symbol
     */
    public String getSymbol()
    {
            return Symbol;
    }
    /**
     *
     * @return String SharesOwned
     */
    public String getSharesOwned()
    {
            return SharesOwned;
    }
    /**
     *
     * @return String ShortRatio
     */
    public String getShortRatio()
    {
            return ShortRatio;
    }
    /**
     *
     * @return String LastTradeTime
     */
    public String getLastTradeTime()
    {
            return LastTradeTime;
    }
    /**
     *
     * @return String TickerTrend
     */
    public String getTickerTrend()
    {
            return TickerTrend;
    }
    /**
     *
     * @return String OneyrTargetPrice
     */
    public String getOneyrTargetPrice()
    {
            return OneyrTargetPrice;
    }
    /**
     *
     * @return String Volume
     */
    public String getVolume()
    {
            return Volume;
    }
    /**
     *
     * @return String HoldingsValue
     */
    public String getHoldingsValue()
    {
            return HoldingsValue;
    }
    /**
     *
     * @return String HoldingsValueRealtime
     */
    public String getHoldingsValueRealtime()
    {
            return HoldingsValueRealtime;
    }
    /**
     *
     * @return String YearRange
     */
    public String getYearRange()
    {
            return YearRange;
    }
    /**
     *
     * @return String DaysValueChange
     */
    public String getDaysValueChange()
    {
            return DaysValueChange;
    }
    /**
     *
     * @return String DaysValueChangeRealtime
     */
    public String getDaysValueChangeRealtime()
    {
            return DaysValueChangeRealtime;
    }
    /**
     *
     * @return String StockExchange
     */
    public String getStockExchange()
    {
            return StockExchange;
    }
    /**
     *
     * @return String DividendYield
     */
    public String getDividendYield()
    {
            return DividendYield;
    }
    /**
     *
     * @param Ask String
     */
    public void setAsk(String Ask)
    {
        this.Ask = Ask;
    }
    /**
     *
     * @param AverageDailyVolume String
     */
    public void setAverageDailyVolume(String AverageDailyVolume)
    {
        this.AverageDailyVolume = AverageDailyVolume;
    }
    /**
     *
     * @param Bid String
     */
    public void setBid(String Bid)
    {
        this.Bid = Bid;
    }
    /**
     *
     * @param AskRealtime String
     */
    public void setAskRealtime(String AskRealtime)
    {
        this.AskRealtime = AskRealtime;
    }
    /**
     *
     * @param BidRealtime String
     */
    public void setBidRealtime(String BidRealtime)
    {
        this.BidRealtime = BidRealtime;
    }
    /**
     *
     * @param BookValue String
     */
    public void setBookValue(String BookValue)
    {
        this.BookValue = BookValue;
    }
    /**
     * NB: this is actually called Change&PercentChange might not work like this
     * @param ChangePercentChange String
     */
    public void setChangePercentChange(String ChangePercentChange)
    {
        this.ChangePercentChange = ChangePercentChange;
    }
    /**
     *
     * @param Change String
     */
    public void setChange(String Change)
    {
        this.Change = Change;
    }
    /**
     *
     * @param Commission String
     */
    public void setCommission(String Commission)
    {
        this.Commission = Commission;
    }
    /**
     *
     * @param ChangeRealtime String
     */
    public void setChangeRealtime(String ChangeRealtime)
    {
        this.ChangeRealtime = ChangeRealtime;
    }
    /**
     *
     * @param AfterHoursChangeRealtime String
     */
    public void setAfterHoursChangeRealtime(String AfterHoursChangeRealtime)
    {
        this.AfterHoursChangeRealtime = AfterHoursChangeRealtime;
    }
    /**
     *
     * @param DividendShare String
     */
    public void setDividendShare(String DividendShare)
    {
        this.DividendShare = DividendShare;
    }
    /**
     *
     * @param LastTradeDate String
     */
    public void setLastTradeDate(String LastTradeDate)
    {
        this.LastTradeDate = LastTradeDate;
    }
    /**
     *
     * @param TradeDate String
     */
    public void setTradeDate(String TradeDate)
    {
        this.TradeDate = TradeDate;
    }
    /**
     *
     * @param EarningsShare String
     */
    public void setEarningsShare(String EarningsShare)
    {
        this.EarningsShare = EarningsShare;
    }
    /**
     *
     * @param ErrorIndicationreturnedforsymbolchangedinvalid String
     */
    public void setErrorIndicationreturnedforsymbolchangedinvalid(String ErrorIndicationreturnedforsymbolchangedinvalid)
    {
        this.ErrorIndicationreturnedforsymbolchangedinvalid = ErrorIndicationreturnedforsymbolchangedinvalid;
    }
    /**
     *
     * @param EPSEstimateCurrentYear String
     */
    public void setEPSEstimateCurrentYear(String EPSEstimateCurrentYear)
    {
        this.EPSEstimateCurrentYear = EPSEstimateCurrentYear;
    }
    /**
     *
     * @param EPSEstimateNextYear String
     */
    public void setEPSEstimateNextYear(String EPSEstimateNextYear)
    {
        this.EPSEstimateNextYear = EPSEstimateNextYear;
    }
    /**
     *
     * @param EPSEstimateNextQuarter String
     */
    public void setEPSEstimateNextQuarter(String EPSEstimateNextQuarter)
    {
        this.EPSEstimateNextQuarter = EPSEstimateNextQuarter;
    }
    /**
     *
     * @param DaysLow String
     */
    public void setDaysLow(String DaysLow)
    {
        this.DaysLow = DaysLow;
    }
    /**
     *
     * @param DaysHigh String
     */
    public void setDaysHigh(String DaysHigh)
    {
        this.DaysHigh = DaysHigh;
    }
    /**
     *
     * @param YearLow String
     */
    public void setYearLow(String YearLow)
    {
        this.YearLow = YearLow;
    }
    /**
     *
     * @param YearHigh String
     */
    public void setYearHigh(String YearHigh)
    {
        this.YearHigh = YearHigh;
    }
    /**
     *
     * @param HoldingsGainPercent String
     */
    public void setHoldingsGainPercent(String HoldingsGainPercent)
    {
        this.HoldingsGainPercent = HoldingsGainPercent;
    }
    /**
     *
     * @param AnnualizedGain String
     */
    public void setAnnualizedGain(String AnnualizedGain)
    {
        this.AnnualizedGain = AnnualizedGain;
    }
    /**
     *
     * @param HoldingsGain String
     */
    public void setHoldingsGain(String HoldingsGain)
    {
        this.HoldingsGain = HoldingsGain;
    }
    /**
     *
     * @param HoldingsGainPercentRealtime String
     */
    public void setHoldingsGainPercentRealtime(String HoldingsGainPercentRealtime)
    {
        this.HoldingsGainPercentRealtime = HoldingsGainPercentRealtime;
    }
    /**
     *
     * @param HoldingsGainRealtime String
     */
    public void setHoldingsGainRealtime(String HoldingsGainRealtime)
    {
        this.HoldingsGainRealtime = HoldingsGainRealtime;
    }
    /**
     *
     * @param MoreInfo String
     */
    public void setMoreInfo(String MoreInfo)
    {
        this.MoreInfo = MoreInfo;
    }
    /**
     *
     * @param OrderBookRealtime String
     */
    public void setOrderBookRealtime(String OrderBookRealtime)
    {
        this.OrderBookRealtime = OrderBookRealtime;
    }
    /**
     *
     * @param MarketCapitalization String
     */
    public void setMarketCapitalization(String MarketCapitalization)
    {
        this.MarketCapitalization = MarketCapitalization;
    }
    /**
     *
     * @param MarketCapRealtime String
     */
    public void setMarketCapRealtime(String MarketCapRealtime)
    {
        this.MarketCapRealtime = MarketCapRealtime;
    }
    /**
     *
     * @param EBITDA String
     */
    public void setEBITDA(String EBITDA)
    {
        this.EBITDA = EBITDA;
    }
    /**
     *
     * @param ChangeFromYearLow String
     */
    public void setChangeFromYearLow(String ChangeFromYearLow)
    {
        this.ChangeFromYearLow = ChangeFromYearLow;
    }
    /**
     *
     * @param PercentChangeFromYearLow String
     */
    public void setPercentChangeFromYearLow(String PercentChangeFromYearLow)
    {
        this.PercentChangeFromYearLow = PercentChangeFromYearLow;
    }
    /**
     *
     * @param LastTradeRealtimeWithTime String
     */
    public void setLastTradeRealtimeWithTime(String LastTradeRealtimeWithTime)
    {
        this.LastTradeRealtimeWithTime = LastTradeRealtimeWithTime;
    }
    /**
     *
     * @param ChangePercentRealtime String
     */
    public void setChangePercentRealtime(String ChangePercentRealtime)
    {
        this.ChangePercentRealtime = ChangePercentRealtime;
    }
    /**
     *
     * @param ChangeFromYearHigh String
     */
    public void setChangeFromYearHigh(String ChangeFromYearHigh)
    {
        this.ChangeFromYearHigh = ChangeFromYearHigh;
    }
    /**
     *
     * @param PercebtChangeFromYearHigh String
     */
    public void setPercebtChangeFromYearHigh(String PercebtChangeFromYearHigh)
    {
        this.PercebtChangeFromYearHigh = PercebtChangeFromYearHigh;
    }
    /**
     *
     * @param LastTradeWithTime String
     */
    public void setLastTradeWithTime(String LastTradeWithTime)
    {
        this.LastTradeWithTime = LastTradeWithTime;
    }
    /**
     *
     * @param LastTradePriceOnly String
     */
    public void setLastTradePriceOnly(String LastTradePriceOnly)
    {
        this.LastTradePriceOnly = LastTradePriceOnly;
    }
    /**
     *
     * @param HighLimit String
     */
    public void setHighLimit(String HighLimit)
    {
        this.HighLimit = HighLimit;
    }
    /**
     *
     * @param LowLimit String
     */
    public void setLowLimit(String LowLimit)
    {
        this.LowLimit = LowLimit;
    }
    /**
     *
     * @param DaysRange String
     */
    public void setDaysRange(String DaysRange)
    {
        this.DaysRange = DaysRange;
    }
    /**
     *
     * @param DaysRangeRealtime String
     */
    public void setDaysRangeRealtime(String DaysRangeRealtime)
    {
        this.DaysRangeRealtime = DaysRangeRealtime;
    }
    /**
     *
     * @param FiftydayMovingAverage String
     */
    public void setFiftydayMovingAverage(String FiftydayMovingAverage)
    {
        this.FiftydayMovingAverage = FiftydayMovingAverage;
    }
    /**
     *
     * @param TwoHundreddayMovingAverage String
     */
    public void setTwoHundreddayMovingAverage(String TwoHundreddayMovingAverage)
    {
        this.TwoHundreddayMovingAverage = TwoHundreddayMovingAverage;
    }
    /**
     *
     * @param ChangeFromTwoHundreddayMovingAverage String
     */
    public void setChangeFromTwoHundreddayMovingAverage(String ChangeFromTwoHundreddayMovingAverage)
    {
        this.ChangeFromTwoHundreddayMovingAverage = ChangeFromTwoHundreddayMovingAverage;
    }
    /**
     *
     * @param PercentChangeFromTwoHundreddayMovingAverage String
     */
    public void setPercentChangeFromTwoHundreddayMovingAverage(String PercentChangeFromTwoHundreddayMovingAverage)
    {
        this.PercentChangeFromTwoHundreddayMovingAverage = PercentChangeFromTwoHundreddayMovingAverage;
    }
    /**
     *
     * @param ChangeFromFiftydayMovingAverage String
     */
    public void setChangeFromFiftydayMovingAverage(String ChangeFromFiftydayMovingAverage)
    {
        this.ChangeFromFiftydayMovingAverage = ChangeFromFiftydayMovingAverage;
    }
    /**
     *
     * @param PercentChangeFromFiftydayMovingAverage String
     */
    public void setPercentChangeFromFiftydayMovingAverage(String PercentChangeFromFiftydayMovingAverage)
    {
        this.PercentChangeFromFiftydayMovingAverage = PercentChangeFromFiftydayMovingAverage;
    }
    /**
     *
     * @param Name String
     */
    public void setName(String Name)
    {
        this.Name = Name;
    }
    /**
     *
     * @param Notes String
     */
    public void setNotes(String Notes)
    {
        this.Notes = Notes;
    }
    /**
     *
     * @param Open String
     */
    public void setOpen(String Open)
    {
        this.Open = Open;
    }
    /**
     *
     * @param PreviousClose String
     */
    public void setPreviousClose(String PreviousClose)
    {
        this.PreviousClose = PreviousClose;
    }
    /**
     *
     * @param PricePaid String
     */
    public void setPricePaid(String PricePaid)
    {
        this.PricePaid = PricePaid;
    }
    /**
     *
     * @param ChangeinPercent String
     */
    public void setChangeinPercent(String ChangeinPercent)
    {
        this.ChangeinPercent = ChangeinPercent;
    }
    /**
     *
     * @param PriceSales String
     */
    public void setPriceSales(String PriceSales)
    {
        this.PriceSales = PriceSales;
    }
    /**
     *
     * @param PriceBook String
     */
    public void setPriceBook(String PriceBook)
    {
        this.PriceBook = PriceBook;
    }
    /**
     *
     * @param ExDividendDate String
     */
    public void setExDividendDate(String ExDividendDate)
    {
        this.ExDividendDate = ExDividendDate;
    }
    /**
     *
     * @param PERatio String
     */
    public void setPERatio(String PERatio)
    {
        this.PERatio = PERatio;
    }
    /**
     *
     * @param DividendPayDate String
     */
    public void setDividendPayDate(String DividendPayDate)
    {
        this.DividendPayDate = DividendPayDate;
    }
    /**
     *
     * @param PERatioRealtime String
     */
    public void setPERatioRealtime(String PERatioRealtime)
    {
        this.PERatioRealtime = PERatioRealtime;
    }
    /**
     *
     * @param PEGRatio String
     */
    public void setPEGRatio(String PEGRatio)
    {
        this.PEGRatio = PEGRatio;
    }
    /**
     *
     * @param PriceEPSEstimateCurrentYear String
     */
    public void setPriceEPSEstimateCurrentYear(String PriceEPSEstimateCurrentYear)
    {
        this.PriceEPSEstimateCurrentYear = PriceEPSEstimateCurrentYear;
    }
    /**
     *
     * @param PriceEPSEstimateNextYear String
     */
    public void setPriceEPSEstimateNextYear(String PriceEPSEstimateNextYear)
    {
        this.PriceEPSEstimateNextYear = PriceEPSEstimateNextYear;
    }
    /**
     *
     * @param Symbol String
     */
    public void setSymbol(String Symbol)
    {
        this.Symbol = Symbol;
    }
    /**
     *
     * @param SharesOwned String
     */
    public void setSharesOwned(String SharesOwned)
    {
        this.SharesOwned = SharesOwned;
    }
    /**
     *
     * @param ShortRatio String
     */
    public void setShortRatio(String ShortRatio)
    {
        this.ShortRatio = ShortRatio;
    }
    /**
     *
     * @param LastTradeTime String
     */
    public void setLastTradeTime(String LastTradeTime)
    {
        this.LastTradeTime = LastTradeTime;
    }
    /**
     *
     * @param TickerTrend String
     */
    public void setTickerTrend(String TickerTrend)
    {
        this.TickerTrend = TickerTrend;
    }
    /**
     *
     * @param OneyrTargetPrice String
     */
    public void setOneyrTargetPrice(String OneyrTargetPrice)
    {
        this.OneyrTargetPrice = OneyrTargetPrice;
    }
    /**
     *
     * @param Volume String
     */
    public void setVolume(String Volume)
    {
        this.Volume = Volume;
    }
    /**
     *
     * @param HoldingsValue String
     */
    public void setHoldingsValue(String HoldingsValue)
    {
        this.HoldingsValue = HoldingsValue;
    }
    /**
     *
     * @param HoldingsValueRealtime String
     */
    public void setHoldingsValueRealtime(String HoldingsValueRealtime)
    {
        this.HoldingsValueRealtime = HoldingsValueRealtime;
    }
    /**
     *
     * @param YearRange String
     */
    public void setYearRange(String YearRange)
    {
        this.YearRange = YearRange;
    }
    /**
     *
     * @param DaysValueChange String
     */
    public void setDaysValueChange(String DaysValueChange)
    {
        this.DaysValueChange = DaysValueChange;
    }
    /**
     *
     * @param DaysValueChangeRealtime String
     */
    public void setDaysValueChangeRealtime(String DaysValueChangeRealtime)
    {
        this.DaysValueChangeRealtime = DaysValueChangeRealtime;
    }
    /**
     *
     * @param StockExchange String
     */
    public void setStockExchange(String StockExchange)
    {
        this.StockExchange = StockExchange;
    }
    /**
     *
     * @param DividendYield String
     */
    public void setDividendYield(String DividendYield)
    {
        this.DividendYield = DividendYield;
    }
}
